// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailablePorts():Promise<Array<string>>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowMessage(arg1:string):Promise<void>;
