// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailablePorts() {
  return window['go']['main']['App']['GetAvailablePorts']();
}

export function RunCmd(arg1, arg2) {
  return window['go']['main']['App']['RunCmd'](arg1, arg2);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowMessage(arg1) {
  return window['go']['main']['App']['ShowMessage'](arg1);
}
